language: go
go: 1.9

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libgtk-3-dev libappindicator3-dev tree gettext
- export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _ | cut -d '_' -f 1-2)

install:
- go get -t -tags gtk_${GTK_VERSION} -v ./...

script:
- ./build_package.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
  - proxychanger_inst.tar.gz
  on:
    repo: okelet/proxychanger
    tags: true
